# Generated by Django 4.2.20 on 2025-05-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждён'), ('shipped', 'В пути'), ('ready_for_pickup', 'Готов к выдаче'), ('delivered', 'Доставлен'), ('returned', 'Возвращён'), ('unclaimed', 'Невостребован')], db_index=True, default='pending', max_length=20),
        ),
    ]
