# Generated by Django 4.2.20 on 2025-05-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'В пути'), ('ready_for_pickup', 'Готов к выдаче'), ('delivered', 'Доставлен'), ('returned', 'Возвращен'), ('unclaimed', 'Просрочен')], db_index=True, default='shipped', max_length=20),
        ),
    ]
