# Generated by Django 4.2.20 on 2025-04-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0002_alter_shop_logo_shopcreationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcreationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='shopcreationrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopcreationrequest',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='shopcreationrequest',
            name='logo',
            field=models.ImageField(blank=True, default='shops/logos/default.jpg', null=True, upload_to='shops/logos/'),
        ),
        migrations.AlterField(
            model_name='shopcreationrequest',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shopcreationrequest',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
