# Generated by Django 4.2.20 on 2025-05-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0003_alter_shopcreationrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, default='shops/default_shop_logo.jpg', null=True, upload_to='shops/'),
        ),
        migrations.AlterField(
            model_name='shopcreationrequest',
            name='logo',
            field=models.ImageField(blank=True, default='shops/default_shop_logo.jpg', null=True, upload_to='shops/'),
        ),
    ]
