# Generated by Django 4.2.20 on 2025-05-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0004_alter_shop_logo_alter_shopcreationrequest_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcreationrequest',
            name='logo',
            field=models.ImageField(blank=True, default='images/default-logo.jpg', null=True, upload_to='bids/'),
        ),
    ]
