# Generated by Django 4.2.20 on 2025-05-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0006_alter_shop_logo_alter_shopcreationrequest_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcreationrequest',
            name='logo',
            field=models.ImageField(blank=True, default='shops/default-logo.jpg', null=True, upload_to='shops/'),
        ),
    ]
