# Generated by Django 4.2.20 on 2025-04-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/images/default.jpg', null=True, upload_to='products/images/'),
        ),
    ]
