# Generated by Django 4.2.20 on 2025-05-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/default_product_image.jpg', null=True, upload_to='products/'),
        ),
    ]
